### PR TITLE
MM-21015 - Replace bytes.Buffer with strings.Builder in mm/gorp

### PR DESCRIPTION
**Pull request by reflog**
#### Summary
strings.Builder is a faster and cheaper way to build strings without needless allocations.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21015

### CODE REVIEW

**Review by jwilander — APPROVED** [review]
LGTM

**Review by crspeller — APPROVED** [review]

**Comment by agnivade** [comment]
I am wondering whether we could add any micro-benchmarks around this to show what sort of gains we got ?

**Comment by ethervoid** [comment]
Why don't we make a PR to the gorp project with these changes?

**Comment by jwilander** [comment]
@ethervoid we have upstreamed to gorp before, totally agree that we should do that for this too 👍 Thoughts @reflog ?

**Comment by reflog** [comment]
@jwilander @ethervoid - I am all for upstreaming this, added it to my todo list :)
just as an FYI our fork is really far behind the main one. I've discussed this with @grundleborg and we'll need to decide - if we want to continue using gorp, we need to sync up.

**Pull request merged**
