### PR TITLE
Make set unique together idempotent upstream

### PR DESCRIPTION
**Pull request by nelsam**
:wave: gorp maintainer here, just making a PR for a PR on our upstream repo.  It doesn't really do anything other than replace the named loop with a function and merge master in.  I'd still appreciate someone on mattermost/gorp double-checking my logic to make sure it's functionally equivalent to the original PR.  I make some pretty dumb mistakes sometimes :)

### CODE REVIEW

**Comment by nelsam** [comment]
Corresponding upstream PR: go-gorp/gorp#372 (just to get them linked)

**Comment by jwilander** [comment]
Whoops, sorry @nelsam this slipped under my radar. @lieut-data mind taking a look? I think you're more familiar with the changes this is related to

**Comment by nelsam** [comment]
no problem :)

**Review by lieut-data — APPROVED** [review]
Looks good to me!

**Review by jwilander — APPROVED** [review]

**Pull request merged**
